
package com.soap.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.soapapp.ObjectFactory;
import com.soapapp.Services;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SoapApps", targetNamespace = "http://www.soapapp.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SoapApps {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.soapapp.Services>
     */
    @WebMethod
    @WebResult(name = "AutoServices", targetNamespace = "")
    @RequestWrapper(localName = "getServiceByCatv2", targetNamespace = "http://www.soapapp.com", className = "com.soapapp.GetServiceByCatv2")
    @ResponseWrapper(localName = "getServiceByCatv2Response", targetNamespace = "http://www.soapapp.com", className = "com.soapapp.GetServiceByCatv2Response")
    public List<Services> getServiceByCatv2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod(action = "fetch_services")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchServices", targetNamespace = "http://www.soapapp.com", className = "com.soapapp.FetchServices")
    @ResponseWrapper(localName = "fetchServicesResponse", targetNamespace = "http://www.soapapp.com", className = "com.soapapp.FetchServicesResponse")
    public List<String> fetchServices();

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addService", targetNamespace = "http://www.soapapp.com", className = "com.soapapp.AddService")
    @ResponseWrapper(localName = "addServiceResponse", targetNamespace = "http://www.soapapp.com", className = "com.soapapp.AddServiceResponse")
    public boolean addService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServiceByCat", targetNamespace = "http://www.soapapp.com", className = "com.soapapp.GetServiceByCat")
    @ResponseWrapper(localName = "getServiceByCatResponse", targetNamespace = "http://www.soapapp.com", className = "com.soapapp.GetServiceByCatResponse")
    public List<String> getServiceByCat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
